server:
  port: 8085
  http2:
    enabled: true
  tomcat:
    redirect-context-root: false
  servlet:
    session:
      # Set HTTP session idle timeout to 2 hours
      timeout: 2h

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: WebTemplate
  devtools:
    restart:
      # Trigger full restart on any changes under src/main/resources/static
      # Override Boot's default exclude list (which normally ignores static/**)
      exclude: ""
  thymeleaf:
    cache: false
  web:
    resources:
      add-mappings: true
  cache:
    type: caffeine
    cache-names: documentStore, anotherCache
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m
  mail:
    host: smtp.gmail.com
    port: 587
    username: permits.pdx@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

info:
  app:
    name: ${spring.application.name}
    description: WebTemplate Spring Boot application
    version: ${project.version:2.0}

#management:
#  endpoints:
#    web:
#      # Explicitly expose basic endpoints over HTTP
#      exposure:
#        include: health,info
#  endpoint:
#    health:
#      show-details: when_authorized
#      probes:
#        enabled: true
#  info:
#    env:
#      enabled: true
#    java:
#      enabled: true
#    os:
#      enabled: true

# RavenDB Configuration
ravendb:
  database: v2.fithub.mcquarrie.cc
  url: http://raven.dell.mcquarrie.cc

logging:
  level:
    root: INFO
    net.ravendb.client: WARN
    org:
      gpc4j:
        web:
          repository: WARN
  pattern:
    dateformat: MM-dd HH:mm:ss.SSSS,America/Los_Angeles
    console: "${CONSOLE_LOG_PATTERN:-%clr(%d{HH:mm:ss.SSSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(%-25.35logger{1}.%M){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"

