spring:
  boot:
    admin:
      client:
        url: http://sba.sba-java25:8085
        username: admin
        password: ENC(YF5nbwQbVtJBzr5EvLyQK5WfLaRtbTefao3v8zncUZkkNLMsZISEs+6ELmnV3UH6)
        auto-registration: true
        auto-deregistration: true
        instance:
          name: ${spring.application.name}
          prefer-ip: true
          management-base-url: http://${POD_IP}:8090

# RavenDB Configuration
ravendb:
  url: http://raven.raven:8080

application:
  tag-watchdog-timer: 60000

logging:
  level:
    root: INFO
    net.ravendb.client: WARN
    de.codecentric.boot.admin.client: INFO
  pattern:
    dateformat: MM-dd HH:mm:ss.SSSS,America/Los_Angeles
    console: "${CONSOLE_LOG_PATTERN:-%clr(%d{HH:mm:ss.SSSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(%-25.35logger{1}.%M){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"

