
spring:
  boot:
    admin:
      client:
        username: client
        password: 714df93cf5c9
        url: http://svc.sba-k8s:8099
        auto-deregistration: true
        instance:
          management-base-url: http://${POD_IP}:8090
          service-host-type: ip
          prefer-ip: true

# RavenDB Configuration
ravendb:
  url: http://raven.raven:8080

logging:
  level:
    root: INFO
    net.ravendb.client: WARN
  pattern:
    dateformat: MM-dd HH:mm:ss.SSSS,America/Los_Angeles
    console: "${CONSOLE_LOG_PATTERN:-%clr(%d{HH:mm:ss.SSSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(%-25.35logger{1}.%M){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"

